# Site
title: Marta Sierosławska
title2: Software developer in test
bio: ""
description: ""
description_long: >- # this means to ignore newlines until "baseurl:"
  This is page is a playground and a notebook for my experiments. I would like
  to document here my programming progress and write down all the notes
  I might need later.
locale: en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
background_image:   /images/bg.jpg
show_excerpts: true
excerpt_separator: <!--more-->

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:year/:month/:day/:title/"
    layout: post
    author:

collections:
  articles:
    output: true

# Jekyll
permalink:          /:year/:month/:day/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social
github:  msieroslawska
linkedin: martasieroslawska

# Personal
location: Munich, Germany
# phone:
# email: your-email@example.com

show_excerpts: true
excerpt_separator: <!--more-->
rss: Subscribe

plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
