name: Marta Sierosławska
title: Software developer in test
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is page is a playground and a notebook for my experiments. I would like
  to document here my programming progress and write down all the notes
  I might need later.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  articles:
    output: true
  codelogs:
    output: true

# Social
github:  msieroslawska
linkedin: martasieroslawska
hackerrank: msieroslawska
location: Munich, Germany

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package.json
  - _site/
